In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [8]:
data = pd.read_csv('customer_engagement_data (1).csv')
data

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
0,1001,56,33,24.93,4,20,25,0
1,1002,46,51,434.94,0,21,9,0
2,1003,32,43,183.53,1,27,2,0
3,1004,60,37,204.61,7,8,15,0
4,1005,25,12,61.39,2,25,3,0
...,...,...,...,...,...,...,...,...
495,1496,37,47,12.49,7,15,9,0
496,1497,41,23,350.90,9,27,21,1
497,1498,29,46,33.90,6,16,24,0
498,1499,52,43,270.98,5,7,34,1
499,1500,50,47,481.44,5,7,22,1

In [14]:
data.head(6)

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
0,1001,56,33,24.93,4,20,25,0
1,1002,46,51,434.94,0,21,9,0
2,1003,32,43,183.53,1,27,2,0
3,1004,60,37,204.61,7,8,15,0
4,1005,25,12,61.39,2,25,3,0
5,1006,38,3,371.33,9,8,49,1

In [16]:
data.tail()

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
495,1496,37,47,12.49,7,15,9,0
496,1497,41,23,350.90,9,27,21,1
497,1498,29,46,33.90,6,16,24,0
498,1499,52,43,270.98,5,7,34,1
499,1500,50,47,481.44,5,7,22,1

In [18]:
data.describe()

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,1250.500000,41.278000,30.214000,262.214180,4.406000,14.062000,25.210000,0.452000
std,144.481833,13.389072,17.166875,139.296217,2.897232,8.870825,14.007939,0.498189
min,1001.000000,18.000000,1.000000,10.120000,0.000000,0.000000,1.000000,0.000000
25%,1125.750000,30.000000,15.000000,147.415000,2.000000,6.000000,13.750000,0.000000
50%,1250.500000,42.000000,30.000000,269.040000,4.000000,14.000000,25.000000,0.000000
75%,1375.250000,52.000000,46.000000,377.982500,7.000000,21.250000,37.000000,1.000000
max,1500.000000,64.000000,59.000000,499.680000,9.000000,29.000000,49.000000,1.000000

In [26]:
data.dtypes

Customer_ID          int64
Age                  int64
Tenure_Months        int64
Monthly_Spend      float64
Support_Tickets      int64
Email_Opens          int64
Website_Visits       int64
Engaged              int64
dtype: object

In [28]:
data.columns

Index(['Customer_ID', 'Age', 'Tenure_Months', 'Monthly_Spend',
       'Support_Tickets', 'Email_Opens', 'Website_Visits', 'Engaged'],
      dtype='object')

In [30]:
data.info

<bound method DataFrame.info of      Customer_ID  Age  Tenure_Months  Monthly_Spend  Support_Tickets  \
0           1001   56             33          24.93                4
1           1002   46             51         434.94                0
2           1003   32             43         183.53                1
3           1004   60             37         204.61                7
4           1005   25             12          61.39                2
..           ...  ...            ...            ...              ...
495         1496   37             47          12.49                7
496         1497   41             23         350.90                9
497         1498   29             46          33.90                6
498         1499   52             43         270.98                5
499         1500   50             47         481.44                5

     Email_Opens  Website_Visits  Engaged
0             20              25        0
1             21               9        0
2             27               2        0
3              8              15        0
4             25               3        0
..           ...             ...      ...
495           15               9        0
496           27              21        1
497           16              24        0
498            7              34        1
499            7              22        1

[500 rows x 8 columns]>

In [36]:
print(data['Website_Visits'].value_counts(dropna=False))

Website_Visits
21    21
4     15
22    15
25    14
6     14
24    14
46    13
44    13
49    12
10    12
20    12
32    11
19    11
37    11
28    11
34    11
30    11
40    11
47    10
3     10
36    10
26    10
42    10
43    10
16    10
15    10
39    10
45     9
14     9
5      9
35     9
41     9
12     9
27     9
9      9
18     9
11     9
2      9
33     9
48     8
31     8
7      8
13     8
8      7
17     7
38     7
29     6
1      6
23     5
Name: count, dtype: int64

In [38]:
print(data['Email_Opens'].value_counts(dropna=False))

Email_Opens
27    25
7     22
2     22
20    21
1     21
4     20
22    19
3     19
19    19
9     18
17    18
28    17
29    17
16    17
12    17
21    17
8     17
6     17
5     16
0     16
18    14
13    14
15    14
24    14
14    13
25    13
11    12
23    12
10    11
26     8
Name: count, dtype: int64

In [42]:
data.nunique()

Customer_ID        500
Age                 47
Tenure_Months       59
Monthly_Spend      497
Support_Tickets     10
Email_Opens         30
Website_Visits      49
Engaged              2
dtype: int64

In [44]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [46]:
data.isnull()

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False

In [50]:
data = data[data['Monthly_Spend'] < 10000]
data

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged
0,1001,56,33,24.93,4,20,25,0
1,1002,46,51,434.94,0,21,9,0
2,1003,32,43,183.53,1,27,2,0
3,1004,60,37,204.61,7,8,15,0
4,1005,25,12,61.39,2,25,3,0
...,...,...,...,...,...,...,...,...
495,1496,37,47,12.49,7,15,9,0
496,1497,41,23,350.90,9,27,21,1
497,1498,29,46,33.90,6,16,24,0
498,1499,52,43,270.98,5,7,34,1
499,1500,50,47,481.44,5,7,22,1

In [54]:
data['Monthly_Spend_log'] = np.log1p(data['Monthly_Spend'])
data

,Customer_ID,Age,Tenure_Months,Monthly_Spend,Support_Tickets,Email_Opens,Website_Visits,Engaged,Monthly_Spend_log
0,1001,56,33,24.93,4,20,25,0,3.255401
1,1002,46,51,434.94,0,21,9,0,6.077505
2,1003,32,43,183.53,1,27,2,0,5.217812
3,1004,60,37,204.61,7,8,15,0,5.325981
4,1005,25,12,61.39,2,25,3,0,4.133405
...,...,...,...,...,...,...,...,...,...
495,1496,37,47,12.49,7,15,9,0,2.601949
496,1497,41,23,350.90,9,27,21,1,5.863347
497,1498,29,46,33.90,6,16,24,0,3.552487
498,1499,52,43,270.98,5,7,34,1,5.605729
499,1500,50,47,481.44,5,7,22,1,6.178857

In [64]:
# Drop 'Engaged' and 'Customer_ID' from features
X = data.drop(columns=['Customer_ID', 'Engaged'])

# Target column
y = data['Engaged']

In [66]:
X = sm.add_constant(X)

In [68]:
model = sm.Logit(y, X).fit()


print(model.summary())

Optimization terminated successfully.
         Current function value: 0.361978
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                Engaged   No. Observations:                  500
Model:                          Logit   Df Residuals:                      492
Method:                           MLE   Df Model:                            7
Date:                Sun, 27 Apr 2025   Pseudo R-squ.:                  0.4743
Time:                        01:26:39   Log-Likelihood:                -180.99
converged:                       True   LL-Null:                       -344.27
Covariance Type:            nonrobust   LLR p-value:                 1.279e-66
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const               -37.9437      4.663     -8.137      0.000     -47.083     -28.804
Age                   0.0066      0.010      0.657      0.511      -0.013       0.026
Tenure_Months        -0.0063      0.008     -0.810      0.418      -0.022       0.009
Monthly_Spend        -0.0254      0.004     -6.115      0.000      -0.033      -0.017
Support_Tickets       0.0014      0.045      0.031      0.975      -0.087       0.090
Email_Opens           0.1635      0.019      8.494      0.000       0.126       0.201
Website_Visits        0.1320      0.014      9.703      0.000       0.105       0.159
Monthly_Spend_log     7.1250      0.996      7.157      0.000       5.174       9.076
=====================================================================================